# fly.toml

app = "next-npm-test"
primary_region = "waw"

[build]
  image = "node:18.12.1"

  # Add environment variables here
  env = [
    "NPM_TOKEN=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",
    # Add other environment variables if needed
  ]

[deploy]
  release_command = "npm run build"
  process = "app"
  port = 3000

[env]
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = [80, 443, 3000]
