# fly.toml

app = "next-npm-test"
primary_region = "waw"

[build]
  image = "node:18.12.1"

  # Add environment variables here
  env = [
    "NPM_TOKEN=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",
    # Add other environment variables if needed
  ]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
